### PR TITLE
Ds 45 refactor pagination

### PR DESCRIPTION
**Pull request by oddaspa**
Changes:
* Renamed file `convert.py` to `time.py`
* Refactored `GetDates` and changed name to `TimeIterator`
* Refactored `GetItems` and changed name to `ItemIterator`
* Added RFC3339 to time delta function in `time.py`
* Minor changes to names in `time.py` to be more precise
* Refactored `@iterator` wrapper to use said iterators
* Removed unnecessary methods
* Added `__add__()` functionality to `SelectItemsResponse` model and `GenericResponse` model
* Updated tests to fit new response

Caveats:
- Iterator only supports `JSONRPC` calls with method `clarify.SelectItems`
- `__add__()` functionality only supports Responses of type `SelectItemsResponse`

### CODE REVIEW

**Comment by oddaspa** [comment]
> When I run `client.select_items_data(ids = ["c941jjrfgiru45pdka50"], not_before = "2020-10-01T12:00:00Z", before = "2022-11-10T12:00:00Z",rollup = "P1DT")`
> 
> I get
> 
> Screenshot 2022-04-08 at 17 51 54
> 
> Not sure why...

I fixed a couple bugs. Should be working now! Please review again :)

**Comment by AlexiaArtemis** [comment]
Yes this works now, great 🙌

I tried also the select_items_data(), and select_items_metadata() methods without parameters. I got a different behaviour for each method.

For the select_items_metadata:

Screenshot 2022-04-20 at 11 26 59

For the select_items_data I get the data from the first 10 items, which is as expected.

**Comment by oddaspa** [comment]
> ...
> For the select_items_metadata method with the limit parameter I got the same message as above.

I can see from [the docs](https://docs.clarify.io/api/1.1beta1/methods/clarify/select-items#item-select-view) that the API has updated its response. I need to update our models to fit their response.

**Comment by oddaspa** [comment]
The problem with too large response from the API. When using rollup the `limit=100` should be fine. 

Code example to verify:
```python
from pyclarify.client import ClarifyClient
from datetime import timedelta

td = timedelta(days=1)
client = ClarifyClient("./clarify-credentials.json")

r = client.select_items_data(limit=100, rollup=td)

print(r)
```

**Comment by AlexiaArtemis** [comment]
Yes it seems fine now 🙌

I get also `jsonrpc='2.0' id='1' result=None error=Error(code='-32015', message='Try again later: internal API request not sent', data=ErrorData(trace='2975a04889fb007781007967db404205', params=None))` error messages when changing the limit to something bigger. 

Does `select_items_data(limit = 190, before = "2021-11-02T21:50:06Z", not_before = "2020-11-02T21:50:06Z")` work for you?  For me no...

**Comment by oddaspa** [comment]
> 

Yes, it does work! However due to the size of the data, some of the responses are too big to be sent through JSONRPC (from the backend) and result in the `"Try again later"` error. This is not an issue with the pagination, but the backend.

**Comment by AlexiaArtemis** [comment]
Ok that's great! Great work 🙌

**Review by AlexiaArtemis — APPROVED** [review]

**Pull request merged**
