### PR TITLE
add Item model and update publish_signals method

### PR DESCRIPTION
**Pull request by oddaspa**
Tested towards prod for setting items visible.

### CODE REVIEW

**Comment by AlexiaArtemis** [comment]
Looks good but I can not make it work... can it be that there is some bug in how the connection is for: itemsBySignal, itemsBySignal -> SignalInfo ? Can you add an example? :)

**Comment by AlexiaArtemis** [comment]
or that the __init__ file has to be updated, with `Item`

**Comment by oddaspa** [comment]
I have updated the tests and exposed Item in the export. You can look at the `test_client_publish_signals.py` as an example :)

**Comment by AlexiaArtemis** [comment]
Quick note:  `Access to item data` should be turned on

Screenshot 2022-01-10 at 13 41 28

Looks great

**Review by AlexiaArtemis — APPROVED** [review]

**Pull request merged**
