### PR TITLE
Ds 38 create filter model in pydantic

### PR DESCRIPTION
**Pull request by oddaspa**
Adding a Filter model to create filters and combining them.

Filter is based on MongoDB filters and works as described in [the docs](https://docs.clarify.io/api/1.1beta1/methods/filter-syntax).

Usage:

```python
from pyclarify.__utils__ import filter

f1 = filter.Filter(fields={"name": filter.NotEqual(value="Lufttemperatur")})
f2 = filter.Filter(fields={"labels.unit-type": filter.NotIn(value=["Flåte", "Merde 5"])})

f1.to_query()
>>> {'name': {'$ne': 'Lufttemperatur'}}

f3 = f1 & f2
f3.to_query()
>>> {
>>>     '$and': [
>>>         {'name': {'$ne': 'Lufttemperatur'}},
>>>         {'labels.unit-type': {'$nin': ['Flåte', 'Merde 5']}}
>>>     ]
>>>}
```

Complete list of operators:
* Equal
* NotEqual
* Regex
* In
* NotIn
* LessThan
* GreaterThan
* GreaterThanOrEqual

What is not included in this PR.
- Consolidate (see discussion # team-data-science in Slack)
- Range operator

### CODE REVIEW

**Comment by AlexiaArtemis** [comment]
Really good work 🚀 🥇

**Review by AlexiaArtemis — APPROVED** [review]
Works as expected 💪

**Review by zehsilva — APPROVED** [review]
Very good work. Given that it might become a common class for the end-user, might be worth importing in the `__init__.py` of the root folder (so that the user can access it via `from pyclarify import Filter`).

**Comment by oddaspa** [comment]
> Very good work. Given that it might become a common class for the end-user, might be worth importing in the `__init__.py` of the root folder (so that the user can access it via `from pyclarify import Filter`).

Yes, I was thinking about that. However, there are these sub classes of Operators (`NotEqual`, `Regex`, etc) that is also in the `filter.py` module. Should we split the `Filter` class into a standalone module, and create an `Operators` module. E.g:

```python
from pyclarify import Filter
from pyclarify.operators import *
```

Or should the operators also be exposed on the top level?
e.g:
```python
from pyclarify import ClarifyClient, Filter, NotIn, Regex

```

**Comment by oddaspa** [comment]
Ended up with this structure:

```python
from pyclarify import filter


f1 = filter.Filter(fields={"name": filter.NotEqual(value="Lufttemperatur")})
f2 = filter.Filter(fields={"labels.unit-type": filter.NotIn(value=["Flåte", "Merde 5"])})

f = f1 & f2 
print(f.to_query()) 
>>> {'$and': [{'name': {'$ne': 'Lufttemperatur'}}, {'labels.unit-type': {'$nin': ['Flåte', 'Merde 5']}}]}
```

**Pull request merged**
